// Generated by webapp-chat-bridge skill — do not edit by hand.
// To regenerate: ~/.claude/skills/webapp-chat-bridge/scripts/install.sh --force --speech-url ...
// If SPEECH_CONFIG.url is empty, the voice UI stays hidden.
export const SPEECH_CONFIG = {
  url: "/speech",
  lang: "de",
  ttsVoice: "de_DE-thorsten-medium",
};
